spring:
  r2dbc:code=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    url: r2dbc:mysql://localhost:3306/pethelpbd?useUni
    username: root
    password: admin
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc: DEBUG
    com.perros.registro_perros: DEBUG
    org.springframework.web: DEBUG
    com.perros.registro_perros.controller: DEBUG
    com.perros.registro_perros.service: DEBUG
    com.perros.registro_perros.repository: DEBUG
    root: INFO

server:
  port: 8080
