spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/pethelpbd
    username: root
    password: admin
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc: DEBUG
server:
  port: 8080
