spring:
  r2dbc:
    url: r2dbc:mysql://mainline.proxy.rlwy.net:58888/railway
    username: root
    password: DvxvtXXjuhZcqpkQEYkzINSxJPaQNGPj
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc: DEBUG
server:
  port: 8080